<?php
namespace IJVR\PublishBundle\Entity;

 
use Doctrine\ORM\EntityRepository;
 
/**
 * WorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */



class AuthorRepository extends EntityRepository
{
    

    public function getAuthorsText($author)
     {
    $query = $this->getEntityManager()
            ->createQuery(
            'SELECT a FROM IJVRPublishBundle:Author a            
            WHERE  a.name LIKE :author' 
        )->setParameter('author', '%'.$author.'%');

   
        $result= $query->getResult();
        return $result ;
    }

   
        
}

?>
