ijvr_platform_view:
    path:     /article/{id}
    defaults: { _controller: IJVRPlatformBundle:Default:view }
oc_platform_view_slug:
    path:      /{year}/{slug}.{format}
    defaults:  { _controller: IJVRPlatformBundle:Default:viewSlug }
ijvr_platform_home:
    path:     /
    defaults: { _controller: IJVRPlatformBundle:Default:home }